# Generated by Django 5.1.3 on 2024-12-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
